### ISSUE TITLE
Write-Log fails when Set-LogTarget = win event log in PowerShell Core

### ISSUE THREAD

**Issue by MarkIannucci** [brandonmcclure/friendly-chainsaw#61]
**Describe the bug**
Write-log throws the following message when you send the output to the event log in PowerShell core:
```
Error Message = The term 'Write-EventLog' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**To Reproduce**
1.  Set-logTargets -WindowsEventLog 1 
2.  Write-log "my thingy"

**Expected behavior**
It goes into event viewer

**Screenshots**
Incidentally, I found this in Windows Server 2019 Event Viewer:

![image](https://user-images.githubusercontent.com/16762974/102168865-41f6da00-3e4e-11eb-95a6-595b5f3d0a26.png)

**Additional context**
I'm going to switch to Write-host and see what sort of output goes to the event viewer

**Comment by brandonmcclure** [comment]
I really should spend some time getting these to work properly in pwsh core, These were originally written targeting powershell 5.1. You can try using [Powershell Compatibility mode](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_windows_powershell_compatibility?view=powershell-7) to load the module that `Write-EventLog` lives in, however there are some caveats that are listed in that doc, and there appears to be an [open bug](https://github.com/PowerShell/PowerShell/issues/13198) that could cause a large number of these compatibility modules to accumulate on your computer. 

Running these commands produced a Windows Event log as I would expect 
```
Import-Module Microsoft.PowerShell.Management -UseWindowsPowerShell
Import-Module FC_Log
Set-logTargets -WindowsEventLog 1
Write-Log "Test"
````
The ps environment I ran in:
```
PS C:\Users\bmcclure> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0
PSEdition                      Core
GitCommitId                    7.1.0
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by brandonmcclure** [comment]
@MarkIannucci, I am completing a PR today that will give a better error to indicate how to set the compatibility mode. I added a comment to you in the PR, but not sure if the at mention worked. 

Comment is: https://github.com/brandonmcclure/friendly-chainsaw/pull/63/commits/99a4e0bad62732a5e3e2b5b800f1c6ee0effe6cd
